// <auto-generated />
using EFC_02.Enitities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFC_02.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230516074234_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFC_02.Enitities.CongThuc", b =>
                {
                    b.Property<int>("CongThucID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CongThucID"));

                    b.Property<int>("DonViTinh")
                        .HasColumnType("int");

                    b.Property<int>("MonAnID")
                        .HasColumnType("int");

                    b.Property<int>("NguyenLieuID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("CongThucID");

                    b.HasIndex("MonAnID");

                    b.HasIndex("NguyenLieuID");

                    b.ToTable("CongThuc");
                });

            modelBuilder.Entity("EFC_02.Enitities.LoaiMonAn", b =>
                {
                    b.Property<int>("LoaiMonAnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiMonAnID"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoaiMonAnID");

                    b.ToTable("LoaiMonAn");
                });

            modelBuilder.Entity("EFC_02.Enitities.MonAn", b =>
                {
                    b.Property<int>("MonAnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonAnID"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiMonAnID")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MonAnID");

                    b.HasIndex("LoaiMonAnID");

                    b.ToTable("MonAn");
                });

            modelBuilder.Entity("EFC_02.Enitities.nguyenLieu", b =>
                {
                    b.Property<int>("NguyenLieuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguyenLieuID"));

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NguyenLieuID");

                    b.ToTable("NguyenLieu");
                });

            modelBuilder.Entity("EFC_02.Enitities.CongThuc", b =>
                {
                    b.HasOne("EFC_02.Enitities.MonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("MonAnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFC_02.Enitities.nguyenLieu", "nguyenLieu")
                        .WithMany("congThucs")
                        .HasForeignKey("NguyenLieuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonAn");

                    b.Navigation("nguyenLieu");
                });

            modelBuilder.Entity("EFC_02.Enitities.MonAn", b =>
                {
                    b.HasOne("EFC_02.Enitities.LoaiMonAn", null)
                        .WithMany("MonAnList")
                        .HasForeignKey("LoaiMonAnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFC_02.Enitities.LoaiMonAn", b =>
                {
                    b.Navigation("MonAnList");
                });

            modelBuilder.Entity("EFC_02.Enitities.nguyenLieu", b =>
                {
                    b.Navigation("congThucs");
                });
#pragma warning restore 612, 618
        }
    }
}
